# Generated by Django 6.0.1 on 2026-01-18 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_review_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#9d50bb', help_text='HEX color для календаря', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Начало')),
                ('end_time', models.DateTimeField(verbose_name='Конец')),
                ('max_capacity', models.IntegerField(default=1, verbose_name='Макс. человек')),
                ('is_personal', models.BooleanField(default=False, verbose_name='Персональная?')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='fitness.trainer')),
                ('workout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fitness.workout')),
            ],
            options={
                'verbose_name': 'Слот расписания',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает'), ('CONFIRMED', 'Подтверждена'), ('CANCELED', 'Отменена')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_bookings', to='fitness.profile')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='fitness.scheduleslot')),
            ],
            options={
                'unique_together': {('slot', 'client')},
            },
        ),
    ]
